"""new class added

Revision ID: 762bdb87a873
Revises: 8083a12f0e40
Create Date: 2024-04-18 22:36:16.683496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762bdb87a873'
down_revision = '8083a12f0e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('grape_variety', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine')
    # ### end Alembic commands ###
